# Generated by Django 2.0 on 2017-12-09 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Favicon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.URLField(unique=True, verbose_name='Domain or subdomain')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='favicons', verbose_name='Path to icon in static files')),
            ],
        ),
    ]
