# Generated by Django 2.0 on 2017-12-09 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=255, verbose_name='Sphinx domain of the reference. e.g. "py" or "std"')),
                ('type', models.CharField(max_length=255, verbose_name='Type of object being linked to, e.g. "mod", "func", "option"')),
                ('project', models.CharField(max_length=255, verbose_name='Project, e.g. py3k, python, sqlalchemy')),
                ('project_version', models.CharField(max_length=255, verbose_name='Version of project documentation')),
                ('target', models.CharField(max_length=255, verbose_name='Docutils/Sphinx target')),
                ('uri', models.URLField(max_length=255, verbose_name='Link to reference')),
                ('display_name', models.CharField(max_length=255, null=True, verbose_name='Optional name for the reference item')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='reference',
            unique_together={('project', 'target', 'type')},
        ),
    ]
